<a href="https://colab.research.google.com/github/franov/analytics/blob/main/Programaci%C3%B3n_Usando_Arreglos_y_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programación usando arreglos y matrices en Python

## Ejercicio 1
El producto escalar de los vectores $\vec{v} = (v_1, v_2..., v_n)$ y $\vec{u} = (u_1, u_2, ..., u_n)$ se puede calcular como:
\begin{equation}
\vec{v}\times\vec{u} = v_1u_1 + v_2u_2 + ... + v_nu_n
\end{equation}

Construya un programa **Python** que lea dos vectores de n elementos y que calcule el producto escalar entre éstos.

* **Entradas**: La entrada al programa está compuesta por un valor entero $n$ mayor que 2. Luego, vienen $2n$ valores reales correspondientes a los elementos de los vectores $\vec{v}$ y $\vec{u}$.
* **Salidas**: La salida del programa es un valor real correspondiente al producto escalar entre los valores de los vectores  $\vec{v}$ y $\vec{u}$.
* **Ejemplo de entrada**: $n = 6$\
\begin{equation}
A = ( 4.0\;\;9.0\;\;6.0\;\;{-1.0}\;\;3.0\;\; {-2.0} )
\end{equation}
\begin{equation}
B = ( {-3.0}\;\;4.0\;\;{-7.0}\;\;1.0\;\;8.0\;\; {-3.0} )
\end{equation}
* **Ejemplo de salida**: $11.0$



In [ ]:
import numpy as np

n = int(input("Ingrese el tamaño de los vectores a multiplicar: "))
A = np.array(list(map(float, input(f"Ingresa los {n} elementos del vector A separados por espacio: ").split())))
B = np.array(list(map(float, input(f"Ingresa los {n} elementos del vector B separados por espacio: ").split())))
print(f"El resultado de la multiplicación de ambos vectores (AxB) es: {np.dot(A, B)}")

Ingrese el tamaño de los vectores a multiplicar: 6
Ingresa los 6 elementos del vector A separados por espacio: 4 9 6 -1 3 -2
Ingresa los 6 elementos del vector B separados por espacio: -3 4 -7 1 8 -3
El resultado de la multiplicación de ambos vectores (AxB) es: 11.0


## Ejercicio 2
Una matriz $A$ es simétrica cuando los elementos $a_{ij}$ son iguales a los $a_{ji}$.\
Escriba un programa **Python** que lea una matriz $A$ de $n \times n$ , con $2 ≤ n < 100$, y que determine si es simétrica.
* **Entradas**: La entrada está compuesta, primero por el valor de $n$ cuyo valor debe ser mayor o igual que 2 y menor que 100. A continuación vendrán $n^2$  valores enteros correspondientes a los valores almacenados en la matriz.
* **Salidas**: La salida del programa puede ser:
    * La matriz es simétrica o
    * La matriz no es simétrica.
* **Ejemplo de entrada**: $n = 3$
\begin{equation}
    A =
\begin{pmatrix}
    4 & 9 & 6 \\
    9 & 0 & −7 \\
    6 & −7 & −1
\end{pmatrix}
\end{equation}
* **Ejemplo de Salida**: La matriz es simétrica.

In [ ]:
import numpy as np

def  is_symmetric (A):
    n, m = A.shape
    for i in range(n):
        for j in range(m):
            if A[i, j] != A[j, i]:
                return False
    return True

n = int(input("Ingrese el tamaño de la matriz cuadrada: "))
if n < 2 or n >= 100:
    print("El tamaño de la matriz debe ser mayor o igual que 2 y menor que 100")
else:
    A = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(n)])

    if is_symmetric(A):
        print("La matriz es simétrica")
    else:
        print("La matriz no es simétrica")

    print(A)


Ingrese el tamaño de la matriz cuadrada: 3
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 4 9 6
Ingrese los elementos de la matriz en la fila 2 separados por espacio: 9 0 -7
Ingrese los elementos de la matriz en la fila 3 separados por espacio: 6 -7 -1
La matriz es simétrica
[[ 4  9  6]
 [ 9  0 -7]
 [ 6 -7 -1]]


## Ejercicio 3
Una matriz $B$ es triangular superior cuando los elementos de la diagonal principal (incluídos) hacia arriba son distintos de cero.\
Escriba un programa **Python** que lea una matriz $B$ de $n \times n$, con $2 ≤ n < 100$, que determine si es triangular superior.
* **Entradas**: La entrada está compuesta, primero por el valor de $n$ cuyo valor debe ser mayor o igual que 2 y menor que 100. A continuación vendrán $n^2$ valores enteros correspondientes a los valores almacenados en la
matriz.
* **Salidas**: La salida del programa puede ser:
    * La matriz es triangular superior o
    * La matriz no es triangular superior
* **Ejemplo de entrada**: $n = 3$
\begin{equation}
    B =
\begin{pmatrix}
    4 & 9 & 6\\
    0 & 0 & −7\\
    0 & 0 & −1
\end{pmatrix}
\end{equation}
* **Ejemplo de Salida**: La matriz no es triangular superior.

In [ ]:
import numpy as np

def  is_triangular (B):
    n, m = B.shape
    for i in range(n):
        for j in range(m):
            if j >= i and B[i, j] == 0:
                return False
    return True

n = int(input("Ingrese el tamaño de la matriz cuadrada: "))
if n < 2 or n >= 100:
    print("El tamaño de la matriz debe ser mayor o igual que 2 y menor que 100")
else:
    B = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(n)])

    if is_triangular(B):
        print("La matriz es triangular superior")
    else:
        print("La matriz no es triangular superior")

    print(B)

Ingrese el tamaño de la matriz cuadrada: 3
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 4 9 6
Ingrese los elementos de la matriz en la fila 2 separados por espacio: 0 0 -7
Ingrese los elementos de la matriz en la fila 3 separados por espacio: 0 0 -1
La matriz no es triangular superior
[[ 4  9  6]
 [ 0  0 -7]
 [ 0  0 -1]]


## Ejercicio 4
Dada una matriz $A = [a_{ij}]$ de orden $n × m$ se define su transpuesta como otra matriz que se representa por $A^T$ y que se obtiene intercambiando ordenadamente las fila por las columnas: $a′_{ji} = a_{ij}, ∀_i = 0, 1, ..., n − 1; ∀_j = 0, 1, ..., m − 1$. Construir un programa **Python** que lea una matriz $A$ de $n × m, (n > 1; m > 1)$ y debe ser leído y que calcule y despliegue la matriz transpuesta $A^T$.

* **Entradas**: La entrada está compuesta, primero por los valores de $n$ y $m$, ambos mayores que 1. A continuación vendrán $n × m$ valores enteros correspondientes a los valores almacenados en la matriz.
* **Salidas**: La salida del programa es una matriz de $m × n$ equivalente a la matriz $A^t$.
* **Ejemplo de entrada**: $n = 3$ y $m = 2$
\begin{equation}
    A =
\begin{pmatrix}
    4 & 9\\
    -7 & 6\\
    0 & -1
\end{pmatrix}
\end{equation}
* **Ejemplo de salida**:
\begin{equation}
    A^T =
\begin{pmatrix}
    4 & -7 & 0\\
    9 & 6 & -1
\end{pmatrix}
\end{equation}

In [4]:
import numpy as np

def transponse_matrix(A):
    n, m = A.shape
    A_t = np.zeros((m, n),)
    for i in range(n):
        for j in range(m):
            A_t[j, i] = A[i, j]

    return A_t


n = int(input("Ingrese el valor de n: "))
m = int(input("Ingrese el valor de m: "))

if n < 2 or m < 2:
    print("El largo y el ancho de la matriz debe ser mayor a 1")
else:
    A = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(m)])
    print(f"La matriz ingresada es: \n{A}")
    A_t = transponse_matrix(A)
    print(f"La matriz transpuesta es: \n{A_t}")


Ingrese el valor de n: 2
Ingrese el valor de m: 3
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 4 9
Ingrese los elementos de la matriz en la fila 2 separados por espacio: -7 6
Ingrese los elementos de la matriz en la fila 3 separados por espacio: 0 -1
La matriz ingresada es: 
[[ 4  9]
 [-7  6]
 [ 0 -1]]
La matriz transpuesta es: 
[[ 4. -7.  0.]
 [ 9.  6. -1.]]


## Ejercicio 5
Una matriz idempotente es un arreglo bidimensional $A$ de $n × n$ que tiene la propiedad $A^2 = A·A = A$.\
Construir un programa **Python** que lea una matriz de $n × n, (n > 1)$ y debe ser leído e indique si la matriz es idempotente.

* **Entradas**: La entrada está compuesta, primero por el valor de n cuyo valor debe ser mayor que 1. A continuación, vendrán $n^2$ valores enteros correspondientes a los valores almacenados en la matriz.
* **Salidas**: La salida del programa puede ser:
    * La matriz es idempotente o
    * La matriz no es idempotente.
* **Ejemplo de entrada**: $n = 2$
\begin{equation}
    A =
\begin{pmatrix}
    2 & -1\\
    2 & -1
\end{pmatrix}
\end{equation}
* **Ejemplo de salida**: La matriz es idempotente

In [ ]:
import numpy as np
n = int(input("Ingrese el tamaño de la matriz cuadrada: "))
A = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(n)])
print(f"La matriz ingresada es: \n{A}")
A2 = np.dot(A, A)

if np.allclose(A, A2):
    print("La matriz es idempotente.")
else:
    print(f"La matriz no es idempotente, su cuadrado es: \n{A2}")

Ingrese el tamaño de la matriz cuadrada: 2
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 2 -1
Ingrese los elementos de la matriz en la fila 2 separados por espacio: 2 -1
La matriz ingresada es: 
[[ 2 -1]
 [ 2 -1]]
La matriz es idempotente.


## Ejercicio 6
La norma L2 se calcula como raíz cuadrada de la suma de los cuadrados de los elementos del vector y también se conoce como norma euclidiana. Es términos simples, se utiliza como la forma de calcular la distancia más corta entre dos puntos en un espacio bidimensional o tridimensional.

Matemáticamente, para un vector $x=[x_1,x_2,...,x_n]$, la norma L2 se define como:
\begin{equation}
||\mathbf{x}||_2 = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2}
\end{equation}

### Aplicaciones de la Norma L2:

* **Medición de Distancias**: Es ampliamente usada para calcular la distancia entre puntos en espacios de múltiples dimensiones, lo cual es fundamental en muchas aplicaciones de análisis de datos y machine learning, como la clasificación de patrones y la agrupación de clústeres.

* **Regularización en Machine Learning**: La norma L2 se utiliza como término de regularización en varios modelos de aprendizaje automático para evitar el sobreajuste. En este contexto, se le llama también regularización Ridge o Tikhonov.

* **Optimización**: Muchos problemas de optimización buscan minimizar alguna función de coste, donde la norma L2 puede actuar como parte de esa función para medir el tamaño o la complejidad de una solución.

* **Geometría y Física**: La norma L2 refleja la idea intuitiva de longitud o distancia en el espacio físico, por lo que tiene aplicaciones directas en geometría y física para describir propiedades como la distancia entre puntos o la magnitud de vectores físicos.


In [83]:
# Calcular la Norma L2 de un vector ingresado
def norma_l2(v):
    norma = (sum(abs(x)**2 for x in v))**0.5
    return norma.round()

v = np.array(list(map(int, input(f"Ingrese los elementos del vector separados por espacio: ").split())))
print(f"El vector ingresado es: {v}")
norma = norma_l2(v)
print(f"La norma del vector es: {norma}")

Ingrese los elementos del vector separados por espacio: 3 1 2 -1 2 4
El vector ingresado es: [ 3  1  2 -1  2  4]
La norma del vector es: 6.0


## Ejercicio 7
Escribe un programa en **Python** que solicite al usuario ingresar las dimensiones $n$ y $p$ para dos matrices, $A$ y $B$, donde $A$ es de tamaño $n \times m$ y $B$ es de tamaño $p \times q$. Luego, el programa debe pedir al usuario que ingrese los elementos de cada matriz y finalmente imprimir el resultado de multiplicar las dos matrices, **sin utilizar la bilbioteca** ***Numpy*** para su manipulación.

In [26]:
def multiplica_matrices(A, B):
    m, n = A.shape
    p, q = B.shape
    C = np.zeros((m, q))
    for i in range(m):
        for j in range(q):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    return C

n = int(input("Ingrese el valor de n: "))
p = int(input("Ingrese el valor de p: "))
A = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz A en la fila {i+1} separados por espacio: ").split())) for i in range(n)])
B = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz B en la fila {i+1} separados por espacio: ").split())) for i in range(p)])
print(f"La matriz A es: \n{A}")
print(f"La matriz B es: \n{B}")
if A.shape[1] != B.shape[0]:
    print(f"No se puede multiplicar las matrices, la forma de A es {A.shape} y de B es {B.shape}")
else:
    C = multiplica_matrices(A, B)
    print(f"La matriz resultante es: \n{C}")

Ingrese el valor de n: 2
Ingrese el valor de p: 2
Ingrese los elementos de la matriz A en la fila 1 separados por espacio: 2 3
Ingrese los elementos de la matriz A en la fila 2 separados por espacio: 4 5
Ingrese los elementos de la matriz B en la fila 1 separados por espacio: 5 6
Ingrese los elementos de la matriz B en la fila 2 separados por espacio: 4 6
La matriz A es: 
[[2 3]
 [4 5]]
La matriz B es: 
[[5 6]
 [4 6]]
La matriz resultante es: 
[[22. 30.]
 [40. 54.]]


## Ejercicio 8
Desarrolla un programa en Python que, dada la matriz $A$ definida como:
\begin{equation}
A =
\begin{pmatrix}
    2 & 2 & 8 & 4\\
    -2 &  5 &  6 &  10\\
    7 & 8 & 9 & 19\\
    1 & 45 & 2 & 18
\end{pmatrix}
\end{equation}
realice los siguientes pasos para verificar si es posible obtener su matriz identidad mediante la multiplicación por su inversa:

* **Calcula el determinante de la matriz $A$**. Si el determinante es igual a 0, el programa debe informar al usuario que la matriz no es invertible y, por lo tanto, no se puede proceder con los cálculos. Si el determinante es diferente de 0, calcula la inversa de la matriz $A$.

* **Multiplica la matriz $A$ por su inversa y muestra el resultado**:  Comprueba y muestra si el resultado de la multiplicación es, efectivamente, la matriz identidad, considerando un margen de error razonable para los cálculos con números de punto flotante.


In [84]:
# Definimos la matriz
A = np.matrix([[2, 2, 8, 4], [-2, 5, 6, 10], [7, 8, 9, 19], [1, 45, 2, 18]])
print(f"La matriz A es: \n{A}")

# Calculamos el determinante
det_A = np.linalg.det(A).round()
print(f"El determinante de la matriz A es: {det_A}")

# Si el determinante es distinto de cero, realizamos la multiplicación de la matriz por su inversa,
# para obtener la matriz identidad
if det_A != 0:
    A_inv = np.linalg.inv(A).round(2)
    print(f"La inversa de la matriz A es: \n{A_inv}")
    print(f"La matriz A multiplicada por su inversa (A^-1) es: \n{np.dot(A, A_inv).round()}" )
else:
    print(f"La matriz no tiene inversa.")

La matriz A es: 
[[ 2  2  8  4]
 [-2  5  6 10]
 [ 7  8  9 19]
 [ 1 45  2 18]]
El determinante de la matriz A es: 24948.0
La inversa de la matriz A es: 
[[ 0.04 -0.18  0.08  0.  ]
 [ 0.03 -0.02 -0.02  0.03]
 [ 0.16  0.02 -0.04 -0.  ]
 [-0.1   0.07  0.05 -0.01]]
La matriz A multiplicada por su inversa (A^-1) es: 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0.  0.  0.  1.]]
