<a href="https://colab.research.google.com/github/franov/analytics/blob/main/Programaci%C3%B3n_Usando_Arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programación usando arreglos y matrices en Python

## Ejercicio 1
El producto escalar de los vectores $\vec{v} = (v_1, v_2..., v_n)$ y $\vec{u} = (u_1, u_2, ..., u_n)$ se puede calcular como:
\begin{equation}
\vec{v}\times\vec{u} = v_1u_1 + v_2u_2 + ... + v_nu_n
\end{equation}

Construya un programa **Python** que lea dos vectores de n elementos y que calcule el producto escalar entre éstos.

* **Entradas**: La entrada al programa está compuesta por un valor entero $n$ mayor que 2. Luego, vienen $2n$ valores reales correspondientes a los elementos de los vectores $\vec{v}$ y $\vec{u}$.
* **Salidas**: La salida del programa es un valor real correspondiente al producto escalar entre los valores de los vectores  $\vec{v}$ y $\vec{u}$.
* **Ejemplo de entrada**: $n = 6$\
\begin{equation}
A = ( 4.0\;\;9.0\;\;6.0\;\;{-1.0}\;\;3.0\;\; {-2.0} )
\end{equation}
\begin{equation}
B = ( {-3.0}\;\;4.0\;\;{-7.0}\;\;1.0\;\;8.0\;\; {-3.0} )
\end{equation}
* **Ejemplo de salida**: $11.0$



In [1]:
import numpy as np

n = int(input("Ingrese el tamaño de los vectores a multiplicar: "))
A = np.array(list(map(float, input(f"Ingresa los {n} elementos del vector A separados por espacio: ").split())))
B = np.array(list(map(float, input(f"Ingresa los {n} elementos del vector B separados por espacio: ").split())))
print(f"El resultado de la multiplicación de ambos vectores (AxB) es: {np.dot(A, B)}")

Ingrese el tamaño de los vectores a multiplicar: 6
Ingresa los 6 elementos del vector A separados por espacio: 4 9 6 -1 3 -2
Ingresa los 6 elementos del vector B separados por espacio: -3 4 -7 1 8 -3
El resultado de la multiplicación de ambos vectores (AxB) es: 11.0


## Ejercicio 2
Una matriz $A$ es simétrica cuando los elementos $a_{ij}$ son iguales a los $a_{ji}$.\
Escriba un programa **Python** que lea una matriz $A$ de $n \times n$ , con $2 ≤ n < 100$, y que determine si es simétrica.
* **Entradas**: La entrada está compuesta, primero por el valor de $n$ cuyo valor debe ser mayor o igual que 2 y menor que 100. A continuación vendrán $n^2$  valores enteros correspondientes a los valores almacenados en la matriz.
* **Salidas**: La salida del programa puede ser:
    * La matriz es simétrica o
    * La matriz no es simétrica.
* **Ejemplo de entrada**: $n = 3$
\begin{equation}
\begin{pmatrix}
    4 & 9 & 6 \\
    9 & 0 & −7 \\
    6 & −7 & −1
\end{pmatrix}
\end{equation}
* **Ejemplo de Salida**: La matriz es simétrica.

In [2]:
import numpy as np

def  is_symmetric (A):
    n, m = A.shape
    for i in range(n):
        for j in range(m):
            if A[i, j] != A[j, i]:
                return False
    return True

n = int(input("Ingrese el tamaño de la matriz cuadrada: "))
if n < 2 or n >= 100:
    print("El tamaño de la matriz debe ser mayor o igual que 2 y menor que 100")
else:
    A = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(n)])

    if is_symmetric(A):
        print("La matriz es simétrica")
    else:
        print("La matriz no es simétrica")

    print(A)


Ingrese el tamaño de la matriz cuadrada: 3
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 4 9 6
Ingrese los elementos de la matriz en la fila 2 separados por espacio: 9 0 -7
Ingrese los elementos de la matriz en la fila 3 separados por espacio: 6 -7 -1
La matriz es simétrica
[[ 4  9  6]
 [ 9  0 -7]
 [ 6 -7 -1]]


## Ejercicio 3
Una matriz $B$ es triangular superior cuando los elementos de la diagonal principal (incluídos) hacia arriba son distintos de cero.\
Escriba un programa **Python** que lea una matriz $B$ de $n \times n$, con $2 ≤ n < 100$, que determine si es triangular superior.
* **Entradas**: La entrada está compuesta, primero por el valor de $n$ cuyo valor debe ser mayor o igual que 2 y menor que 100. A continuación vendrán $n^2$ valores enteros correspondientes a los valores almacenados en la
matriz.
* **Salidas**: La salida del programa puede ser:
    * La matriz es triangular superior o
    * La matriz no es triangular superior
* **Ejemplo de entrada**: $n = 3$
\begin{equation}
\begin{pmatrix}
    4 & 9 & 6\\
    0 & 0 & −7\\
    0 & 0 & −1
\end{pmatrix}
\end{equation}
* **Ejemplo de Salida**: La matriz no es triangular superior.

In [3]:
import numpy as np

def  is_triangular (B):
    n, m = B.shape
    for i in range(n):
        for j in range(m):
            if j >= i and B[i, j] == 0:
                return False
    return True

n = int(input("Ingrese el tamaño de la matriz cuadrada: "))
if n < 2 or n >= 100:
    print("El tamaño de la matriz debe ser mayor o igual que 2 y menor que 100")
else:
    B = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(n)])

    if is_triangular(B):
        print("La matriz es triangular superior")
    else:
        print("La matriz no es triangular superior")

    print(B)

Ingrese el tamaño de la matriz cuadrada: 3
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 4 9 6
Ingrese los elementos de la matriz en la fila 2 separados por espacio: 0 0 -7
Ingrese los elementos de la matriz en la fila 3 separados por espacio: 0 0 -1
La matriz no es triangular superior
[[ 4  9  6]
 [ 0  0 -7]
 [ 0  0 -1]]


## Ejercicio 4
Dada una matriz $A = [a_{ij}]$ de orden $n × m$ se define su transpuesta como otra matriz que se representa por $A^t$ y que se obtiene intercambiando ordenadamente las fila por las columnas: $a′_{ji} = a_{ij}, ∀_i = 0, 1, ..., n − 1; ∀_j = 0, 1, ..., m − 1$. Construir un programa **Python** que lea una matriz $A$ de $n × m, (n > 1; m > 1)$ y debe ser leído y que calcule y despliegue la matriz transpuesta $A^t$.

* **Entradas**: La entrada está compuesta, primero por los valores de $n$ y $m$, ambos mayores que 1. A continuación vendrán $n × m$ valores enteros correspondientes a los valores almacenados en la matriz.
* **Salidas**: La salida del programa es una matriz de $m × n$ equivalente a la matriz $A^t$.
* **Ejemplo de entrada**: $n = 3$ y $m = 2$
\begin{equation}
\begin{pmatrix}
    4 & 9\\
    -7 & 6\\
    0 & -1
\end{pmatrix}
\end{equation}
* **Ejemplo de salida**:
\begin{equation}
    A^t =
\begin{pmatrix}
    4 & -7 & 0\\
    9 & 6 & -1
\end{pmatrix}
\end{equation}

In [4]:
import numpy as np
n = int(input("Ingrese el valor de n: "))
m = int(input("Ingrese el valor de m: "))

if n < 2 or m < 2:
    print("El largo y el ancho de la matriz debe ser mayor a 1")
else:
    A = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(m)])
    print(f"La matriz ingresada es: \n{A}")
    A_t = np.transpose(A)
    print(f"La matriz transpuesta es: \n{A_t}")


Ingrese el valor de n: 2
Ingrese el valor de m: 3
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 4 9
Ingrese los elementos de la matriz en la fila 2 separados por espacio: -7 6
Ingrese los elementos de la matriz en la fila 3 separados por espacio: 0 -1
La matriz ingresada es: 
[[ 4  9]
 [-7  6]
 [ 0 -1]]
La matriz transpuesta es: 
[[ 4 -7  0]
 [ 9  6 -1]]


## Ejercicio 5
Una matriz idempotente es un arreglo bidimensional $A$ de $n × n$ que tiene la propiedad $A^2 = A·A = A$.\
Construir un programa **Python** que lea una matriz de $n × n, (n > 1)$ y debe ser leído e indique si la matriz es idempotente.

* **Entradas**: La entrada está compuesta, primero por el valor de n cuyo valor debe ser mayor que 1. A continuación, vendrán $n^2$ valores enteros correspondientes a los valores almacenados en la matriz.
* **Salidas**: La salida del programa puede ser:
    * La matriz es idempotente o
    * La matriz no es idempotente.
* **Ejemplo de entrada**: $n = 2$
\begin{equation}
\begin{pmatrix}
    2 & -1\\
    2 & -1
\end{pmatrix}
\end{equation}
* **Ejemplo de salida**: La matriz es idempotente

In [5]:
import numpy as np
n = int(input("Ingrese el tamaño de la matriz cuadrada: "))
A = np.matrix([list(map(int, input(f"Ingrese los elementos de la matriz en la fila {i+1} separados por espacio: ").split())) for i in range(n)])
print(f"La matriz ingresada es: \n{A}")
A2 = np.dot(A, A)

if np.allclose(A, A2):
    print("La matriz es idempotente.")
else:
    print(f"La matriz no es idempotente, su cuadrado es: \n{A2}")

Ingrese el tamaño de la matriz cuadrada: 2
Ingrese los elementos de la matriz en la fila 1 separados por espacio: 2 -1
Ingrese los elementos de la matriz en la fila 2 separados por espacio: 2 -1
La matriz ingresada es: 
[[ 2 -1]
 [ 2 -1]]
La matriz es idempotente.
